// <auto-generated />
//
// To parse this JSON data, add NuGet 'System.Text.Json' then do:
//
//    using Utilities_aspnet.Entities.Instagram;
//
//    var instagramUserId = InstagramUserId.FromJson(jsonString);
namespace Utilities_aspnet.Entities.Instagram
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class InstagramUserId
    {
        [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
        public string Status { get; set; }

        [JsonProperty("data", NullValueHandling = NullValueHandling.Ignore)]
        public string Data { get; set; }
    }

    public partial class InstagramUserId
    {
        public static InstagramUserId FromJson(string json) => JsonConvert.DeserializeObject<InstagramUserId>(json, Utilities_aspnet.Entities.Instagram.InstagramUserIdConverter.Settings);
    }

    internal static class InstagramUserIdConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
